name: CMake

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: ubuntu-latest
            generator-argument: DEB
            generator-output: |
              *.deb
          - os: windows-latest
            generator-argument: ZIP
            generator-output: |
              *.zip

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

      - name: Build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Pack
        shell: bash
        run: cpack -G ${{ matrix.generator-argument }}

      - name: Upload result to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kauth-dashboard
          path: ${{ matrix.generator-output }}